Route/searchfilters
WildCodeSchool/healthymood-api pull request #34
Opened 2020-07-10 12:37 UTC by AmelieChevalier

En cours..

2020-07-11 14:55 UTC, AmelieChevalier commented
@ComicScrip la requete SQL fonctionne pour cumuler un mot clé et un ou plusieurs types de plats (testée dans insomnia) mais pour une raison obscure le test correspondant au mot clé simple ne passait plus.. je l'ai supprimé. Mais dans insomnia, juste un mot clé ou juste un type de plat, ça marche aussi.

2020-07-11 14:57 UTC, Gottfrieden commented
@ComicScrip Tout est ok de mon côté

2020-07-12 09:27 UTC, ComicScrip requested changes

2020-07-12 09:27 UTC, ComicScrip commented on models/recipe.model.js
> +      'SELECT DISTINCT recipes.name FROM meal_type_recipes INNER JOIN recipes ON meal_type_recipes.recipe_id = recipes.id WHERE (? is NULL OR meal_type_recipes.meal_type_id IN (?)) AND (? is NULL OR
que se passe-t-il si on cherche une recette n'ayant pas de meal_type lié ?

2020-07-12 09:27 UTC, ComicScrip commented on models/recipe.model.js
> +    const sqlMealTypes = query.meal_types ? query.meal_types.map(mealtype => parseInt(mealtype)) : null;
si sqlMealTypes contient une liste d'identifiants, pourquoi ne pas l'appeler mealTypeIds ? On pourrait croire que c'est une liste d'objets sinon.

2020-07-12 09:27 UTC, ComicScrip commented on tests/recipes-endpoints.test.js
> -  describe(' GET /recipes/?search=keyword', () => {
Peut-être que le test ne passe plus parce que justement vous avez créé une régression. 
Hint : mauvais type de jointure dans le modèle.

2020-07-12 09:27 UTC, ComicScrip commented on models/recipe.model.js
> +  static async findByKeyWord (query) {
renommer en search() vue qu'on ne recherche plus uniquement par mot clé

2020-07-12 09:38 UTC, Gottfrieden commented on models/recipe.model.js
> +      'SELECT DISTINCT recipes.name FROM meal_type_recipes INNER JOIN recipes ON meal_type_recipes.recipe_id = recipes.id WHERE (? is NULL OR meal_type_recipes.meal_type_id IN (?)) AND (? is NULL OR
Si une recette n'a pas de meal type lié elle ne sortira juste pas dans les résultats. C'est l'objectif non ?

2020-07-12 09:40 UTC, AmelieChevalier commented on tests/recipes-endpoints.test.js
> -  describe(' GET /recipes/?search=keyword', () => {
Dans insomnia, à GET /recipes/?search=salade avec ma bdd il me sort 3 recettes de salade même si je ne cherche pas de meal_type, du coup je ne comprends pas pourquoi le test ne passe pas dans les mêmes conditions..

2020-07-12 09:41 UTC, AmelieChevalier commented on models/recipe.model.js
> +    const sqlMealTypes = query.meal_types ? query.meal_types.map(mealtype => parseInt(mealtype)) : null;
yes on change ça

2020-07-12 09:44 UTC, AmelieChevalier commented on models/recipe.model.js
> +      'SELECT DISTINCT recipes.name FROM meal_type_recipes INNER JOIN recipes ON meal_type_recipes.recipe_id = recipes.id WHERE (? is NULL OR meal_type_recipes.meal_type_id IN (?)) AND (? is NULL OR
Enfin si on sélectionne un meal_type dans les filtres, on ne sortira que les recettes qui sont liées à ce meal_type. 
Si on rajoute un mot clé, alors on ne sort que les recettes qui cumulent le mot clé + le bon type de repas. 
Dans l'état actuel, notre composant recherche sort les résultas attendus dans tous les cas de figure (juste un mot clé / juste un meal-type / un mot clé + un meal type)

2020-07-12 09:44 UTC, ComicScrip commented
Vous avez créé un model mealTypeRecipe pour gérer les associations entre une recette et des types de plats. C'est bien, mais certaines méthodes ne serviront probablement à rien. Pareillement, le mealTypesController ne servira à rien. 
Comment je vois les choses : 
- Nous avons besoin de pouvoir lier des types de plats à une recette lors de l'édition de cette dernière (création ou modification). Tout cela va se faire dans les méthodes create() et update() du controlleur des recette, qui feront appel au model mealTypeRecipe. Au moment de la création d'une recette, on récupère une liste d'identifiants de types de plats sur laquelle il faudra itérer pour créer les associations après avoir créé la recette et récupéré son identifiant. Au moment de la mise à jour, on récupère éagalement une liste de types de plats depuis le forumaire, mais cette fois-ci il faudra d'abord supprimer toutes les associations existantes (dans le modèle mealTypeRecipe, changer deleteAll() en deleteAllLinkedToRecipe(recipe_id)) pour récréer les associations avec les identifiants qui proviennent du forumaire par la suite (comme on l'aura fait au niveau de la création d'une recette)
- Nous avons besoin de récupérer les types de plat liés à une recette lors de l'affichage de cette dernière mais aussi pour pré-remplir le formulaire lors de la modification ce cette dernière. Dans la méthode findOne() du controlleur recipe, on pourra faire appel à une méthode getMealtypes(recipeId) dans le modèle recipe qui renverra une liste d'objets mealtype associés à une recette en particulier

2020-07-12 10:23 UTC, AmelieChevalier commented
@ComicScrip on a bien vu ton conseil pour la réorganisation des models et controllers, par contre, même si on comprends l'idée on ne voit pas comment faire, donc on va avancer sur le front avec le back tel quel, et il nous faudra un coup de main pour réorganiser les choses avec toi demain.

2020-07-12 12:18 UTC, Gottfrieden commented on models/recipe.model.js
> +      'SELECT DISTINCT recipes.name FROM meal_type_recipes INNER JOIN recipes ON meal_type_recipes.recipe_id = recipes.id WHERE (? is NULL OR meal_type_recipes.meal_type_id IN (?)) AND (? is NULL OR
Ok on vient de comprendre, on est dessus

2020-07-14 14:33 UTC, AmelieChevalier commented
@ComicScrip Honnêtement je ne comprends pas pourquoi les tests de recipes (qui ne concernent que la recherche simple) ne passent plus alors que sur l'application, ça fonctionne, même quand la recette n'a pas de meal-type renseigné ou tout autre champ manquant.. 
Accessoirement j'ai mergé dev sur cette branche et il y a d'autres tests qui ne passent pas mais ils ne passaient déjà pas sur dev. J'ai laissé de côté. Ce qui est pushé à cet instant fonctionne comme on le souhaite (sauf erreur de ma part)

2020-07-15 07:45 UTC, merged