Hotfix/geoffroy
WildCodeSchool/healthymood-api pull request #51
Opened 2020-07-20 15:16 UTC by Gottfrieden

@ComicScrip J'ai ajouté la requette findBySlug pour les articles

2020-07-22 08:23 UTC, ComicScrip commented
merge please

2020-07-24 08:19 UTC, Gottfrieden commented
@ComicScrip Merge fait

2020-07-27 06:20 UTC, ComicScrip requested changes

2020-07-27 06:20 UTC, ComicScrip commented on models/article.model.js
> +          const err = new Error();
non, laisser ce qu'il y avait avant, sinon régression

2020-07-27 07:34 UTC, merged